name: Stub sources correctness checks

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  pre_commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure the stub example with the stub version argument
        run: idf.py reconfigure -DSERIAL_FLASHER_STUB_PULL_VERSION='0.3.0'
        working-directory: ${{github.workspace}}/examples/esp32_stub_example

      - name: Run git diff to check if the sources in the repo match the generated ones
        run: git diff --exit-code
